// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SerializationConfigurationTypes.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.57)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using Naos.Auth.Serialization.Bson;
using Naos.Auth.Serialization.Json;
using OBeautifulCode.Serialization.Bson;
using OBeautifulCode.Serialization.Json;
using System;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace Naos.Auth.Domain.Test
{
    [ExcludeFromCodeCoverage]
    [GeneratedCode("Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test", "1.55.57")]
    public static class SerializationConfigurationTypes
    {
        public static BsonSerializationConfigurationType BsonSerializationConfigurationType => typeof(AuthBsonSerializationConfiguration).ToBsonSerializationConfigurationType();

        public static JsonSerializationConfigurationType JsonSerializationConfigurationType => typeof(AuthJsonSerializationConfiguration).ToJsonSerializationConfigurationType();
    }
}